### ISSUE TITLE
Support workspaces

### ISSUE THREAD

**Issue by KaelWD** [lropero/upgradeps#2]
- Run in the root as well as all directories listed in `yarn workspaces info`
- Ignore `workspaceDependencies`, currently it tries to upgrade locally-linked private packages to `"^undefined"`

**Comment by lropero** [comment]
Can you provide an example of a failing `package.json` file? I'm not familiar with yarn workspaces.

**Comment by KaelWD** [comment]
At the root: https://github.com/vuetifyjs/vuetify/blob/b377ece4/package.json
Workspace depending on unpublished packages: https://github.com/vuetifyjs/vuetify/blob/b377ece4/packages/docs/package.json

It's not a big deal to fix manually, just an idea if you feel like implementing it.

**Comment by lropero** [comment]
Workspaces still not supported but the `undefined` issue you described is now fixed (v1.2.0).
