### ISSUE TITLE
@nightly version downgraded to @latest

### ISSUE THREAD

**Issue by codebling** [lropero/upgradeps#6]
I have a repo with `parcel@nightly` installed. Running `upgradeps` downgrades this to `@latest`. 
```
parcel ✔ 2.0.0-nightly.577 → 1.12.4
```
I don't *necessarily* expect `upgradeps` to be able to know how to update this package, but it seems like *semantically* it should know that 2.0.0 → 1.12.4 would be a downgrade, and perhaps warn?

**Comment by lropero** [comment]
Since version `1.6.0` semver comparison got refactored, this is most probably no longer an issue.

**Comment by codebling** [comment]
`@nightly` still becomes `@latest`

**Comment by codebling** [comment]
@lropero should we just ignore this edge case

**Comment by lropero** [comment]
> @lropero should we just ignore this edge case

Hey @codebling why not just use the `-s` option for `@nightly` dependencies that you wish to remain unchanged?
